#!/bin/bash

# Called from enrunerate, which does the process handling part

# echo '*** Software Engineer? We''re hiring at ScraperWiki! https://blog.scraperwiki.com/jobs/data-engineer-liverpool-25k-to-35k/ ***'
# echo

echo 'Started run:' `date --rfc-3339=seconds`

# kill after 1 hour
timeout --kill-after=1m 1h ./code/scraper
ERR=$?

# GNU timeout is documented as returning 124 on a timeout
# Also saw cases of 143 = 128 + 15, i.e. a SIGTERM (see https://github.com/scraperwiki/code-scraper-in-browser-tool/issues/131)
if [ "$ERR" == "124" -o "$ERR" == "143" ]
then
  echo "Run stopped by ScraperWiki, taking more than 1 hour"
# 137 = 128 + 9 which is what timeout returns on catching a SIGKILL
elif [ "$ERR" == "137" ]
then
  echo "Run killed by ScraperWiki, taking more than 1 hour, and wouldn't exit upon request"
fi

if [ "$ERR" == "0" ]
then
  curl -s --data "type=ok" "https://scraperwiki.com/api/status" > /dev/null
else
  curl -s --data "type=error" "https://scraperwiki.com/api/status" > /dev/null
fi

echo 'Finished run:' `date --rfc-3339=seconds` 'Exit code:' $ERR
