#!/usr/bin/env php
<?

require 'scraperwiki.php';

$html = scraperwiki::scrape("http://www.flourish.org/blog");
print $html;

# Saving data:
# $unique_keys = array('id');
# $row = array('id'=>12, 'name'=>'violet', 'age'=>7);
# scraperwiki::save_sqlite($unique_keys, $row);

?>

